name: cs230
# Run 
# mamba env update --file environment.yaml 
#to install the packages.
channels:
  - defaults
dependencies:
  - python=3.11
  # for data analysis
  - pandas
  - numpy
  - matplotlib
  # for model
  - pytorch 
  - transformers
  - datasets
  # for jupyter notebook
  - ipykernel
  - ipywidgets
  - widgetsnbextension
  - pandas-profiling
  - pip
  # put your pip packages here
  - pip:
    # for .env file
    - python-dotenv
